### PR TITLE
Add vis.js via npm package

### PR DESCRIPTION
**Pull request by victor-nitu**

### CODE REVIEW

**Comment by Suven** [comment]
If you have contributions / extensions to this addon, I am happy to integrate them @nightsh.

**Comment by victor-nitu** [comment]
Well, I haven't done much to be honest – I'll be using this fork in a project that deals with exposing public procurement networks, so I expect(ed) it to be more specialized than a general purpose addon. So far, nothing had happened much in that direction, so yeah, I am thinking now whether things could just go back upstream. I'll need to think about it a bit.

However, there are still some bits and pieces that I would be able to extract from the fork into separate branches for merging reasons. These are the things I've been thinking about:

* some completions around nodes and edges integration
* an alternative way of defining data sets (not really an improvement though)
* some tentative of easier sharing the selected nodes/edges list with the outer context
* last but not least, add vis using the npm module, as opposed to bower package
  * I've done this because we plan to hack a bit on vis itself, but I've found the npm build is much easier to deal with

Anything here you'd be interested in adopting? I can, as mentioned, prepare an integration branch for each of them. If this goes well, I seriously consider abandoning my fork in favor of the original project.

And hey, thanks a lot for pinging back. You know, this was an accidental PR, I really thought your addon is unmaintained :grin: You gave it a great start, I would've done it in a less elegant way myself, I think, so kudos for this :beers: 

Out of curiosity, what was/is your use case for it? Are you still using this ember addon, or visjs?

Edit: I like your avatar :nerd_face:

**Comment by victor-nitu** [comment]
I'd also be quite keen on introducing 2d charts to the stage, would that be okay with you? That would be a somewhat bigger extension of the original repo, but it would bring more visjs features in. What do you think? At the moment we're using them in an Ember app, but it's kinda "manually crafted".

**Comment by Suven** [comment]
What you are describing as 'not so much' seems like a lot of effort :D

I'm definitly interested in using the npm-module instead of the bower-dep. That seems to be the way to go for all third-party deps from now on and also enables stuff like fastboot and treeshaking.

The completion around node- and edge-integration also seems interesting.

I'll just have a look on the other things you did.

To be honest, the repo is in a semi-maintained state. This is because we needed the networking-stuff for a mobile app which uses visjs to visualize something like the level-paths in candycrush. The as-is-state solved that problem well enough, so I didn't progress further. That said, I still am very much in favor of putting effort into things that enables others to do new stuff. Also, with ember-cli-swiper, I made the experience that the ember-community gives even more back, then what you provide initially. That's something I really love and want to support.

About the 2D-Charts: Currently the plugins name is a bit of a lie, since it only ever cared about the networking. @gossi did a fork/addon for the timeline-parts and also brought up the idea to create smth. like an visjs-core-addon. I really would like the idea to share a codebase for common stuff, but split the rest. I think if you deeply support various visjs-parts you end up with much code that does not really has much DRY-potential. Besides that, visjs is also going to be split into various parts.

You can find gossis thoughts here: almende/vis#3074

Edit:\ lol. Your avatar is nice as well :P

**Comment by gossi** [comment]
I'm up for it! See my comment on the reference issue.

**Comment by victor-nitu** [comment]
So, my initial thoughts re: splitting:

* ember-vis-core
* ember-vis-network (pulling core as a dependency)
* ember-vis-timeline (same)
* etc.

_EDIT: I just realised @gossi mentioned the same structure in the issue, on a second reading. Awesome!_

Not sure I would split at smaller modules level (e.g. clustering) though. What do you guys think?

I have little experience with creating ember addons, but anyway, I'm not afraid of such tasks.

@Suven As for integrating the various bits and pieces I've done to the fork, I'm not tempted to postpone it until we reach any kind of consensus regarding splitting vis into multiple addons. Maybe we end up deprecating everything and starting a new structure / naming convention etc.

However, don't bother trying to decypher my commits to the fork, I can separate them myself into feature branches for easier review. Also needs some testing, which... I... skipped :disappointed:

**Pull request closed without merging**
